image: gitpod/workspace-base

tasks:
- name: Day1/2
  init: |
    chmod 755 /workspace/unimi2025/bin/*
    chmod 755 /workspace/unimi2025/DAY2/bin/*
    sudo apt install bc pigz
  command: |
    cd /workspace
    export PATH=/workspace/unimi2025/bin:$PATH
    export PATH=/workspace/unimi2025/DAY2/bin:$PATH
    export PATH=/workspace/unimi2025/DAY2/bin/pggb:$PATH
workspaceLocation: "/workspace"
